<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-15 16:15
=======
# Generated by Django 6.0.4 on 2026-04-10 12:07
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='cc_courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('years_to_complete', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ga_courses',
            },
        ),
        migrations.CreateModel(
            name='cc_roomassignments',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('building_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('is_airconditioned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cc_roomassignments',
            },
        ),
        migrations.CreateModel(
            name='cc_subjects',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ga_subjects',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4
            name='ga_academicyears',
            fields=[
                ('ay_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ga_academicyears',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='ga_assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Written Work', 'Written Work'), ('Performance Task', 'Performance Task')], max_length=50)),
                ('raw_score', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('due_date', models.DateField()),
            ],
            options={
                'db_table': 'ga_assignment',
            },
        ),
        migrations.CreateModel(
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4
            name='ga_faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ga_faculty',
            },
        ),
        migrations.CreateModel(
            name='ga_gradescale',
            fields=[
                ('scale_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_raw_score', models.FloatField()),
                ('max_raw_score', models.FloatField()),
                ('transmuted_grade', models.FloatField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ga_gradescale',
            },
        ),
        migrations.CreateModel(
            name='ga_sections',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ga_sections',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='ga_students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ga_students',
            },
        ),
        migrations.CreateModel(
            name='ga_subjects',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ga_subjects',
            },
        ),
        migrations.CreateModel(
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4
            name='ga_teacher',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ga_teacher',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='se_students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('extension_name', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('civil_status', models.CharField(max_length=20)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('mother_toungue', models.CharField(max_length=50)),
                ('is_indigenous', models.BooleanField(default=False)),
                ('is_4ps_beneficiary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'se_students',
            },
        ),
        migrations.CreateModel(
            name='cc_classsections',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_level_or_year', models.CharField(max_length=20)),
                ('section_name', models.CharField(max_length=50)),
                ('max_capacity', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.cc_courses')),
                ('ay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_academicyears')),
                ('adviser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.ga_teacher')),
            ],
            options={
                'db_table': 'cc_classsections',
            },
        ),
        migrations.CreateModel(
            name='cc_curriculum',
            fields=[
                ('curriculum_id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_year_start', models.IntegerField()),
                ('effective_year_end', models.IntegerField()),
                ('description', models.TextField()),
                ('is_current_standard', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.cc_courses')),
            ],
            options={
                'db_table': 'ga_curriculum',
            },
        ),
        migrations.CreateModel(
            name='cc_prerequisites',
            fields=[
                ('prereq_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_grade_required', models.FloatField()),
                ('required_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='assessments.cc_subjects')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.cc_subjects')),
            ],
            options={
                'db_table': 'cc_prerequisites',
            },
        ),
        migrations.CreateModel(
            name='cc_coursematerials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=20)),
                ('file_url', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.cc_subjects')),
            ],
            options={
                'db_table': 'cc_coursematerials',
            },
        ),
        migrations.CreateModel(
            name='ga_assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Written Work', 'Written Work'), ('Performance Task', 'Performance Task')], max_length=50)),
                ('raw_score', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('due_date', models.DateField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.cc_subjects')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_sections')),
            ],
            options={
                'db_table': 'ga_assignment',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4
            name='ga_exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('grading_period', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=3)),
                ('exam_type', models.CharField(choices=[('Quarterly', 'Quarterly'), ('Periodic', 'Periodic')], max_length=20)),
                ('max_score', models.PositiveIntegerField()),
                ('exam_date', models.DateField()),
                ('ay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_academicyears')),
<<<<<<< HEAD
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.cc_subjects')),
=======
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_subjects')),
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4
            ],
            options={
                'db_table': 'ga_exam',
            },
        ),
        migrations.CreateModel(
            name='ga_grades',
            fields=[
                ('summary_grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grading_period', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=3)),
                ('initial_grade', models.FloatField()),
                ('transmuted_grade', models.FloatField()),
                ('is_passed', models.BooleanField(default=False)),
                ('ay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_academicyears')),
<<<<<<< HEAD
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.cc_subjects')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.se_students')),
=======
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_subjects')),
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4
            ],
            options={
                'db_table': 'ga_grades',
            },
        ),
        migrations.CreateModel(
            name='ga_rubrics',
            fields=[
                ('rubric_id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_points_per_criteria', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_assignment')),
            ],
            options={
                'db_table': 'ga_rubrics',
            },
        ),
<<<<<<< HEAD
=======
        migrations.AddField(
            model_name='ga_assignment',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_sections'),
        ),
        migrations.CreateModel(
            name='ga_studentgrades',
            fields=[
                ('grade_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_score', models.PositiveIntegerField()),
                ('percentage_score', models.FloatField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('is_late_submission', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_assignment')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_students')),
            ],
            options={
                'db_table': 'ga_studentgrades',
            },
        ),
        migrations.CreateModel(
            name='ga_reportcards',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('general_average', models.FloatField()),
                ('attendance_present', models.IntegerField()),
                ('attendance_absent', models.IntegerField()),
                ('status', models.CharField(choices=[('Promoted', 'Promoted'), ('Retained', 'Retained')], max_length=10)),
                ('issued_date', models.DateField()),
                ('ay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_academicyears')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_students')),
            ],
            options={
                'db_table': 'ga_reportcards',
            },
        ),
        migrations.AddField(
            model_name='ga_assignment',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_subjects'),
        ),
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4
        migrations.CreateModel(
            name='ga_gradeshistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_grade', models.FloatField()),
                ('new_grade', models.FloatField()),
                ('reason_for_change', models.TextField()),
                ('change_timestamp', models.DateTimeField(auto_now_add=True)),
                ('summary_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_grades')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.ga_teacher')),
            ],
            options={
                'db_table': 'ga_gradeshistory',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='cc_coursenotes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.cc_courses')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.ga_teacher')),
            ],
            options={
                'db_table': 'cc_coursenotes',
            },
        ),
        migrations.CreateModel(
            name='cc_classschedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.cc_classsections')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.cc_subjects')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.ga_teacher')),
            ],
            options={
                'db_table': 'cc_classschedules',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4
            name='ga_teacherremarks',
            fields=[
                ('remark_id', models.AutoField(primary_key=True, serialize=False)),
                ('narrative_remark', models.TextField()),
                ('core_values_rating', models.CharField(max_length=100)),
                ('observed_values', models.TextField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_faculty')),
                ('summary_grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_grades')),
            ],
            options={
                'db_table': 'ga_teacherremarks',
            },
        ),
        migrations.CreateModel(
            name='ga_transcripts',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_units_earned', models.IntegerField()),
                ('gpa', models.FloatField()),
                ('graduation_date', models.DateField()),
                ('is_official_copy', models.BooleanField(default=False)),
                ('remarks', models.TextField()),
<<<<<<< HEAD
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.se_students')),
=======
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_students')),
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4
            ],
            options={
                'db_table': 'ga_transcripts',
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='ga_studentgrades',
            fields=[
                ('grade_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(blank=True, choices=[('Exam', 'Exam'), ('Assignment', 'Assignment')], max_length=20, null=True)),
                ('raw_score', models.PositiveIntegerField()),
                ('percentage_score', models.FloatField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('is_late_submission', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.se_students')),
            ],
            options={
                'db_table': 'ga_studentgrades',
            },
        ),
        migrations.CreateModel(
            name='ga_reportcards',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('general_average', models.FloatField()),
                ('attendance_present', models.IntegerField()),
                ('attendance_absent', models.IntegerField()),
                ('status', models.CharField(choices=[('Promoted', 'Promoted'), ('Retained', 'Retained')], max_length=10)),
                ('issued_date', models.DateField()),
                ('ay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.ga_academicyears')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.se_students')),
            ],
            options={
                'db_table': 'ga_reportcards',
            },
        ),
=======
>>>>>>> 174518e34e0d9a80c29f3f23d280ed88bdee9ba4
    ]
