# Generated by Django 6.0.4 on 2026-04-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ga_academicyears',
            new_name='cc_academicyears',
        ),
        migrations.AlterModelTable(
            name='cc_academicyears',
            table='cc_academicyears',
        ),
    ]
